name: Publish Docker images

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-push:
    name: Push Docker images to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: michzimny/cs3api4lab/jupyterlab
          tag_with_ref: true
          tag_with_sha: true
          dockerfile: Dockerfile
